version: "3.7"
services:
  app:
    build:
      args:
        user: poderjudicial
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: poderjudicial
    container_name: poderjudicial-app
    restart: unless-stopped
    ports:
      - "8888:8080"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - poderjudicial

  db:
    image: mysql:8.0
    container_name: poderjudicial-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - poderjudicial

  nginx:
    image: nginx:alpine
    container_name: poderjudicial-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - poderjudicial

networks:
  puntocrypto:
    driver: bridge
